### ISSUE TITLE
1. domaci ukol @akunzova

### ISSUE THREAD

**Issue by jpozlovska** [jpozlovska/PythonNewUkoly#1]

**Comment by akunzova** [comment]
Dobrá práce!:) kod je prehledny, strukturovany a  okomentovany. Nemam moc co dodat. Kdybych byla hnidopich, tak bych napr. v ramci metody ziskej_inicialy()  osetrila, aby inicialy byly vzdy velkymi pismeny bez ohledu, jak jsou zadána. Ale to jsou drobnosti, pisu splneno!

**Comment by jpozlovska** [comment]
Děkuji :-)
